[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.flake8]
max-line-length = 120
ignore = "E203, W503"

[tool.pylint]
ignore-patterns = [
    "(.)*_test\\.py",
    "test_(.)*\\.py"
]
max-line-length = 120

[tool.pylint."MESSAGES CONTROL"]
disable = [
    "logging-fstring-interpolation",
    "broad-exception-caught",
    "missing-function-docstring",
    "missing-module-docstring",
    "missing-class-docstring",
    "too-few-public-methods",
    "too-many-instance-attributes"
]

[tool.pylint.TYPECHECK]
generated-members = "cv2.*"
